  # Learn more at http://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        enabled: yes
        target: 100%
        threshold: 100%
    patch:
      default:
        enabled: yes
        target: 100%
        threshold: 100%

ignore:
  - "R/paper.R"
  - "R/test.R"
  - "tests/testthat/*.R"
