// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_lc_cpp1
NumericMatrix calc_lc_cpp1(NumericVector A, NumericVector lambda, NumericVector w, NumericVector x);
RcppExport SEXP _metabodecon_calc_lc_cpp1(SEXP ASEXP, SEXP lambdaSEXP, SEXP wSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_lc_cpp1(A, lambda, w, x));
    return rcpp_result_gen;
END_RCPP
}
// calc_lc_cpp2
NumericMatrix calc_lc_cpp2(NumericVector A, NumericVector lambda, NumericVector w, NumericVector x);
RcppExport SEXP _metabodecon_calc_lc_cpp2(SEXP ASEXP, SEXP lambdaSEXP, SEXP wSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_lc_cpp2(A, lambda, w, x));
    return rcpp_result_gen;
END_RCPP
}
// calc_lc_cpp3
NumericMatrix calc_lc_cpp3(NumericVector A_, NumericVector lambda_, NumericVector w_, NumericVector x_);
RcppExport SEXP _metabodecon_calc_lc_cpp3(SEXP A_SEXP, SEXP lambda_SEXP, SEXP w_SEXP, SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda_(lambda_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_(w_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_lc_cpp3(A_, lambda_, w_, x_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metabodecon_calc_lc_cpp1", (DL_FUNC) &_metabodecon_calc_lc_cpp1, 4},
    {"_metabodecon_calc_lc_cpp2", (DL_FUNC) &_metabodecon_calc_lc_cpp2, 4},
    {"_metabodecon_calc_lc_cpp3", (DL_FUNC) &_metabodecon_calc_lc_cpp3, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_metabodecon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
