# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_lc_cpp1 <- function(A, lambda, w, x) {
    .Call('_metabodecon_calc_lc_cpp1', PACKAGE = 'metabodecon', A, lambda, w, x)
}

calc_lc_cpp2 <- function(A, lambda, w, x) {
    .Call('_metabodecon_calc_lc_cpp2', PACKAGE = 'metabodecon', A, lambda, w, x)
}

calc_lc_cpp3 <- function(A_, lambda_, w_, x_) {
    .Call('_metabodecon_calc_lc_cpp3', PACKAGE = 'metabodecon', A_, lambda_, w_, x_)
}

