# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check
permissions: read-all
on: {
  push: {branches: [main, master]},
  pull_request: {branches: [main, master]}
}
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release', bioc: true}
          - {os: windows-latest, r: 'release', bioc: true}
          - {os: windows-latest, r: 'oldrel-4', bioc: true}
          - {os: ubuntu-latest,  r: 'release', bioc: false}
          - {os: ubuntu-latest,  r: 'release', bioc: true}
          - {os: ubuntu-latest,  r: 'oldrel-1', bioc: true}
          - {os: ubuntu-latest,  r: 'oldrel-2', bioc: true}
          - {os: ubuntu-latest,  r: 'oldrel-3', bioc: true}
          - {os: ubuntu-latest,  r: 'oldrel-4', bioc: true}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RUN_SLOW_TESTS: "TRUE"
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: https://spang-lab.r-universe.dev

      - name: Set up R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, mdrb=?ignore-before-r=4.3.0
          needs: check

      - name: Install MacOS System Dependencies
        uses: r-hub/actions/setup-r-sysreqs@v1
        with: { type: "minimal" }

      - name: Install Linux System Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libgsl0-dev

      - name: Test package
        uses: r-lib/actions/check-r-package@v2
        env: { _R_CHECK_FORCE_SUGGESTS_: false }

      - name: Test package without Bioconductor Deps
        if: ${{ !matrix.config.bioc }}
        env: { _R_CHECK_FORCE_SUGGESTS_: false }
        run: |
          # Remove Bioconductor dependencies and reinstall speaq without them
          Rscript -e "remove.packages(c('MassSpecWavelet', 'impute'))"
          Rscript -e "install.packages(c('speaq'))"
          # Call R CMD check manually, as the r-lib action notices that speaq
          # (mandatory dependency) cannot be imported without impute and
          # MassSpecWavelet and therefore does not even try to run R CMD check.
          cd ..
          R CMD build metabodecon
          R CMD check --no-manual --as-cran metabodecon_*.tar.gz