# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: R-CMD-check
on: {
  push: {branches: [main, master]},
  pull_request: {branches: [main, master]}
}

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel-4'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}
          - {os: ubuntu-latest,  r: 'oldrel-3'}
          # We do not test for oldrel-4 on Linux, because the most recent
          # version of randomForst (4.7-1) requires R >= 4.1.0 and for some
          # reason `pak::pkg_install()` is not (yet) smart enough to figure
          # out that it can just install randomForest 4.6-14 instead. On
          # Windows this works just fine, so we test it there and hope that
          # `install.packages()` is smarter than `pak::pkg_install()`.
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RUN_SLOW_TESTS: "TRUE"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install MacOS System Dependencies
        uses: r-hub/actions/setup-r-sysreqs@v1
        with: {type: "minimal"}

      - name: Install Linux System Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libgsl0-dev

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with: { extra-packages: "any::rcmdcheck", needs: "check" }

      - name: Install required Rust Targets on Windows
        if: runner.os == 'Windows'
        run: rustup target add i686-pc-windows-gnu

      - name: Test package
        uses: r-lib/actions/check-r-package@v2
