name: Install-check
permissions: read-all

on: {
  push: {branches: [main, master]},
  pull_request: {branches: [main, master]}
}

jobs:

  test-modern-cran-install:
    runs-on: ${{ matrix.config.os }}
    name: CRAN Modern, ${{ matrix.config.os }}, ${{ matrix.config.r }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RUN_SLOW_TESTS: "TRUE"
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: 'none'
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: https://spang-lab.r-universe.dev

      - name: Test modern Installation from CRAN
        run: Rscript scripts/test-install.R CRAN-Modern

      - name: Test old-school Installation from CRAN
        run: Rscript scripts/test-install.R CRAN-Old

      - name: Test Installation from Github
        run: Rscript scripts/test-install.R Github
