# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
name: test-coverage
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with: {use-public-rspm: true}
      - name: Install MacOS System Dependencies
        uses: r-hub/actions/setup-r-sysreqs@v1
        with: {type: "minimal"}
      - name: Install Linux System Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libgsl0-dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: {extra-packages: "any::covr", needs: "coverage"}
      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
